blank_issues_enabled: false
contact_links:
  - name: 🚀 CrazyJMB Website
    url: https://crazyjmb.com
    about: Visit my main website for more projects and information.
  - name: 📧 Personal Contact
    url: mailto:contact@crazyjmb.com
    about: Send me an email for urgent issues or private matters.
